#!/usr/bin/env python3

import re
import sys

# fmt: off
CHARSET: dict[str, str] = {
  " _TOP":" ",
  " _BOT":" ",

  # Alphabet
  "A_TOP":"▄▀█", "B_TOP":"█▄▄", "C_TOP":"▄▀▀", "D_TOP":"█▀▄",
  "A_BOT":"█▀█", "B_BOT":"█▄█", "C_BOT":"▀▄▄", "D_BOT":"█▄▀",

  "E_TOP":"█▀▀", "F_TOP":"█▀▀", "G_TOP":"█▀▀", "H_TOP":"█░█",
  "E_BOT":"██▄", "F_BOT":"█▀░", "G_BOT":"█▄█", "H_BOT":"█▀█",

  "I_TOP":"▀█▀", "J_TOP":"░█", "K_TOP":"█▄▀", "L_TOP":"█░░",
  "I_BOT":"▄█▄", "J_BOT":"▄▀", "K_BOT":"█░█", "L_BOT":"█▄▄",

  "M_TOP":"█▀▄▀█", "N_TOP":"█▄░█", "O_TOP":"█▀█", "P_TOP":"█▀█",
  "M_BOT":"█░▀░█", "N_BOT":"█░▀█", "O_BOT":"█▄█", "P_BOT":"█▀▀",

  "Q_TOP":"█▀█░", "R_TOP":"█▀█", "S_TOP":"█▀", "T_TOP":"▀█▀",
  "Q_BOT":"█▄▀▄", "R_BOT":"█▀▄", "S_BOT":"▄█", "T_BOT":"░█░",

  "U_TOP":"█░█", "V_TOP":"█░█", "W_TOP":"█░█░█", "X_TOP":"▀▄▀",
  "U_BOT":"█▄█", "V_BOT":"▀▄▀", "W_BOT":"▀▄▀▄▀", "X_BOT":"▄▀▄",

  "Y_TOP":"▀▄▀", "Z_TOP":"▀▀▄",
  "Y_BOT":"░█░", "Z_BOT":"▄█▄",

  # Numericals
  "0_TOP":"▄▀▄", "1_TOP":"▀█░", "2_TOP":"▀▀▄", "3_TOP":"▀█▄", "4_TOP":"█░█",
  "0_BOT":"▀▄▀", "1_BOT":"▄█▄", "2_BOT":"▄█▄", "3_BOT":"▄▄▀", "4_BOT":"▀▀█",

  "5_TOP":"██▀", "6_TOP":"█▀▀", "7_TOP":"▀▀█", "8_TOP":"███", "9_TOP":"███",
  "5_BOT":"▄▄█", "6_BOT":"███", "7_BOT":"░█░", "8_BOT":"█▄█", "9_BOT":"▄▄█",

  # Other Characters
  "!_TOP":"█", ":_TOP":"▀", ";_TOP":"⠀▀", "<_TOP":"▄▀",
  "!_BOT":"▄", ":_BOT":"▀", ";_BOT":"▄▀", "<_BOT":"⠀▀",

  "=_TOP":"▀▀", ">_TOP":"▀▄", "._TOP":"⠀", ",_TOP":"⠀⠀",
  "=_BOT":"▀▀", ">_BOT":"▀⠀", "._BOT":"▀", ",_BOT":"▄▀",

  "|_TOP":"█", "+_TOP":"▄█▄", "-_TOP":"▄▄", "__TOP":"⠀⠀⠀",
  "|_BOT":"█", "+_BOT":"⠀▀⠀", "-_BOT":"⠀⠀", "__BOT":"▄▄▄",

  "(_TOP":"▄▀", ")_TOP":"▀▄", "[_TOP":"█▀", "]_TOP":"▀█", "{_TOP":"░█", "}_TOP":"█░",
  "(_BOT":"▀▄", ")_BOT":"▄▀", "[_BOT":"█▄", "]_BOT":"▄█", "{_BOT":"▀▄", "}_BOT":"▄▀",

  "/_TOP":"⠀▄▀", "\\_TOP":"▀▄⠀",
  "/_BOT":"▄▀⠀", "\\_BOT":"⠀▀▄",
}
# fmt: on


SPLIT_RE = re.compile(r"\x1B\[\d+(?:;\d+){0,4}m|.")


def main() -> None:
    offset = 1
    clean = False
    if sys.argv[1] in ["-c", "--clean"]:
        offset += 1
        clean = True

    text = " ".join(sys.argv[offset:])
    # Process escape sequences (eg: "\x1B")
    text = bytes(text, "utf-8").decode("unicode_escape")
    # Split ANSI codes and characters, filter newlines out
    chars = re.findall(SPLIT_RE, text)

    top = ""
    bot = ""
    length = 0
    for char in chars:
        # Normal character
        if len(char) == 1:
            char = char.upper()
            if length > 0:
                top += " "
                bot += " "
            top += CHARSET.get(f"{char}_TOP", "   ")
            bot += CHARSET.get(f"{char}_BOT", "   ")
            length += 1
        # ANSI code
        else:
            top += char
            bot += char
    if clean:
        top = top.replace("░", " ")
        bot = bot.replace("░", " ")
    print(top)
    print(bot)


if __name__ == "__main__":
    main()
